import React, { Component } from 'react';

import './App.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import Sidebar from './components/Sidebar';
import Content from './components/Content';

// main wrapper for the frontend application
class App extends Component {
    // initialise the state properties 
    state = {
        showOutput: false,
        query: null
    }

    // pass new query generated by QueryForm to the Content component for it to be processed and created.
    submitQuery = (keywords, tweetsPerLocation, locations) => {
        const query = {
            keywords: keywords,
            max_tweets_per_request: tweetsPerLocation,
            locations: locations
        }
        
        this.setState({ 
            showOutput: true,
            query: query
        })
    }

    // change the showOutput state variable to ensure consistency between components
    setShowOutput = (display) => {
        this.setState({
            showOutput: display
        })
    }


    render() {

        return (
            <div className="App">
                {/* 
                the submitQuery function is passed as a prop to the Sidebar (and then QueryForm) component allowing the child components to access this function.
                this allows the child component to pass up data to the parent, which can then be communicated to anothe child component, namely Content
                */}
                <Sidebar createQuery={this.submitQuery} />
                <Content showOutput={this.state.showOutput} setShowOutput={this.setShowOutput} newQuery={this.state.query} />
            </div>
        );
    }
}

export default App;
