import React, { Component } from 'react';

import './App.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import Sidebar from './components/Sidebar';
import Content from './components/Content';

// main wrapper for the frontend
class App extends Component {
    state = {
        showOutput: false,
        query: null
    }

    // pass new query generated by QueryFor to Content component for it to be processed and created
    submitQuery = (keywords, tweetsPerLocation, locations) => {
        const query = {
            keywords: keywords,
            max_tweets_per_request: tweetsPerLocation,
            locations: locations
        }
        
        this.setState({ 
            showOutput: true,
            query: query
        })
    }

    // change the showOutput state variable to ensure consistency between components
    setShowOutput = (display) => {
        this.setState({
            showOutput: display
        })
    }


    render() {

        return (
            <div className="App">
                <Sidebar createQuery={this.submitQuery} />
                <Content showOutput={this.state.showOutput} setShowOutput={this.setShowOutput} newQuery={this.state.query} />
            </div>
        );
    }
}

export default App;
